resources:
  - volume.yaml
  - metallb.yaml
  - ./nginx/nginx.yaml
  - ./mysql/mysql.yaml
  - ./wordpress/wordpress.yaml
  - ./phpmyadmin/phpmyadmin.yaml
  - ./ftps/ftps.yaml
  - ./influx/influx.yaml
  - ./grafana/grafana.yaml